apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-cert-ITEM
spec:
  secretName: ingress-ITEM-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: ITEM.topzone.me
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - ITEM.topzone.me
    - ITEM.default.topzone-k8s.topzone.me
